# Site Settings
title: scriptbox | No choice
email: bnjddiwebmaster@gmail.com
description: source code for free.
baseurl: "/scriptbox" # the subpath of your site, e.g. /blog
url: "https://bnjddi.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: scriptbox
user_description: enjoy with us Our motto is free resources for everyone.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: World-Trends-Channel-1278791588964027
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 40
paginate_path: "/page/:num/"
svg_color: "#f34573"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: SEO TOOLS
    url: /category/seo/
  - title: wordpress-plugins
    url: /category/wordpress-plugins/
  - title: wordpress themes
    url: /category/wordpress-themes/
  - title: joomla themes
      url: /category/joomla-themes/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
